syrup_component_api_options:
    path:     /{params}
    defaults: { _controller: SyrupComponentBundle:Api:options, params: 0, _format: json }
    methods:  [OPTIONS]
    requirements:
        params: ".+"

syrup_component_api_run:
    path:     /{componentName}/run
    defaults: { _controller: SyrupComponentBundle:Api:run, _format: json }
    methods:  [POST]
