parameters:
    uploader:
        aws-access-key: ***REMOVED***
        aws-secret-key: ***REMOVED***
        s3-upload-path: keboola-logs/debug-files
        bitly-login:    ***REMOVED***
        bitly-api-key:  ***REMOVED***

services:
    syrup.componentbundle.listener.exception:
        class: Syrup\ComponentBundle\Listener\SyrupExceptionListener
        arguments: [@logger, @syrup.monolog.json_formatter]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    syrup.componentbundle.listener.controller:
        class: Syrup\ComponentBundle\Listener\SyrupControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    syrup.component_factory:
        class: Syrup\ComponentBundle\Component\ComponentFactory
        arguments: [@logger, @doctrine, %components%]
    syrup.monolog.s3_uploader:
        class: Syrup\ComponentBundle\Monolog\Uploader\SyrupS3Uploader
        arguments: [%uploader%]
    syrup.monolog.json_formatter:
        class: Syrup\ComponentBundle\Monolog\Formatter\SyrupJsonFormatter
        arguments: [%app_name%, @syrup.monolog.s3_uploader]
    syrup.routing_loader:
        class: Syrup\ComponentBundle\Routing\Loader
        arguments: [%components%]
        tags:
            - { name: routing.loader }
    syrup.temp_factory:
        class: Syrup\ComponentBundle\Filesystem\TempServiceFactory
        arguments: [%components%]
    storageApi:
        class: Keboola\StorageApi\Client
        arguments: [%storageApi.test.token%]
