branches:
  only:
    - master
sudo: false
language: php
php:
  - '5.6'
  - '5.4'
services:
  - mysql
  - elasticsearch
before_script:
  - mysql -e 'create database syrup;'
  - composer self-update
  - composer install -n --no-scripts
after_script:
  - vendor/bin/test-reporter
addons:
  code_climate:
    repo_token:
      secure: "qJ3cK2F45P9XcysH0Hf3W6Bai+Bdv5POdd3A4xqlN2sYpimbjAxi1ncTIEGtd6PVQ+x2cejiq5C92OxKz7MHZDOMNErKeVLFItFuVEGEQpq1v9LsVgJztodfYpaMSVFUnEaGTDQ+TRcMnsjzLrFWpTR/jyYvfbD7ffxAXjTS1q8="
notifications:
  slack:
    secure: I73TdwZCz04fIrLIM8kctaZd6uyVhqBZXs1L6wFC2lhyUFX+L5kxKRldOyBrQp1v5SL+wkuok+CBPmqxa1e75fWYA7Zsi/VpH+XFnG2zCjuq1+v9wXjiWMVp75aL24kcsm6WiXqqpEIrpnaO99+nXDuT9+Os/+0COW0wN1sfwjg=
